class Settings:
    DEVICE_HOST = '127.0.0.1'
    DEVICE_PORT = 8000

    TELEMETRY_DELAY_SEC = 1
    TELEMETRY_LOG = 'telemetry_log.log'
    TELEMETRY_TIME_MIN = 1

    SCPI_DELIMITER = '\n'

    HTTP_API_SERVER='127.0.0.1'
    HTTP_API_PORT=8001

